name: colbert-v0.2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip=20.2.2
  - cudatoolkit=11.1
  - pytorch=1.8.2
  - torchvision=0.9.2
  - faiss-gpu=1.7.2
  - pip:
    - tensorboard
    - mlflow
    - tqdm
    - transformers==3.0.2
    - ujson

